### PR TITLE
Custom marshalling for Network based on purpose

### PR DESCRIPTION
**Pull request by joshuaspence**
Partly fixes paultyng/terraform-provider-unifi#107. Without this change, performing any modification to a network was causing the network to become disassociated from the gateway (see screenshots in the original issue).

I'm not sure if this is the best fix, but it works...

### CODE REVIEW

**Comment by joshuaspence** [comment]
I'm not sure why so many of the generated files were changed.

**Comment by paultyng** [comment]
I think it was just missing a `gofmt -s`

**Comment by paultyng** [comment]
Hmm, I take that back, unsure what is going on here, let me reset it.

**Comment by paultyng** [comment]
Possibly run against a different version of the controller.

**Comment by paultyng** [comment]
I think the fix that needs to happen here is to mark some of the fields that are defaulted server side to "Computed"  in the provider, that will allow the server to set it and then Terraform will round trip the values. Not sure if I'm fully understanding this issue though.

**Comment by joshuaspence** [comment]
Changing the provider won't help. The problem seems to be that `go-unifi` sends too many fields in the request. This is my theory at least. So for example if you create a LAN network but the POST request has WAN fields such as `wan_networkgroup` then the UniFi controller gets confused and you end up in a weird inconsistent state that you can't get into from the UI. The real problem here is that the API doesn't seem to do enough input validation.

**Comment by paultyng** [comment]
I see what you are saying, that makes sense.  There are a couple ways to approach this, we can do the `omitempty`, but maybe we should be more selective on it. And anything where the zero value is actually used (ie. empty string or zero is valid) we'd have to make it a pointer. Alternatively we could override the marshalling to exclude fields in certain scenarios by writing a custom `MarshalJSON` method. That may be easier and offer more control, unsure.

**Comment by joshuaspence** [comment]
Yeah, I agree with you and I wasn't thrilled with the implementation either. I mainly wanted to verify that my suspicion was correct (seems like it is) and get some feedback from you before I proceed. I think the biggest issue with my current approach is that you can't unset string fields because setting any string value to empty string will just silently omit it from the request.

I agree that pointer vaues would be better, but I am not sure how to figure out which fields should be nullable and which should not without reverse engineering the API. I know that you extracted JSON data from the Unifi controller, does that data give any indication of nullable fields?

**Comment by paultyng** [comment]
The java seems to be obfuscated, so all I've been able to extract where these regex validation strings for some fields:

https://github.com/paultyng/go-unifi/blob/a3d437ef8e2491953829a6a4e29944ac7e40d3d5/fields/6.0.23/NetworkConf.json#L131

And then I just use some (very naive) heuristics to translate that to type and marshalling information. But essentially it also just entails a lot of manual overriding and tweaking, observations of the API usage, etc. to get it all working.

**Comment by joshuaspence** [comment]
Alright. I'm thinking I will just convert enough fields to be nullable that it fixes my immediate problem.

**Comment by paultyng** [comment]
Just a couple other thoughts here. You could override `MarshalJSON` to do basically what you are doing in the provider, marshal different structs based on the data, see this: https://github.com/paultyng/go-unifi/blob/9e8fe73b8512faa22f5aceeda8705edf449e110c/unifi/account.go#L8-L26

Also, if you can create a failing test in the provider on a PR, happy to do this as well. I can possibly create one from your examples, just haven't give it a shot yet.

**Comment by joshuaspence** [comment]
The trick used for `Account` doesn't quite work here... it doesn't seem to allow you to remove fields from the marshalled JSON (using `json:"-"`).

**Comment by paultyng** [comment]
Yeah I think in the function we'd just have to have multiple branches that used fully new structs instead of embedding. Pretty tedious, but would give the full control.

**Comment by joshuaspence** [comment]
To clarify, you mean that you are fine with the current approach? If so, I'll clean it up and get it ready for review.

**Comment by paultyng** [comment]
Its pretty gross but yeah I think its fine for now 😄 As long as the tests are passing. I think we should just ensure we get some tests in the provider that fail without this to make sure we don't cause any regressions.

**Comment by joshuaspence** [comment]
Will come back to this

**Pull request closed without merging**
