### PR TITLE
Add methods to site management

### PR DESCRIPTION
**Pull request by kurtmc**
I've added some methods for site management as I want to update the terraform provider to allow me to manage sites (https://github.com/paultyng/terraform-provider-unifi/issues/16). I just thought I would open this PR early so you can let me know if this conforms to the right style.

### CODE REVIEW

**Comment by paultyng** [comment]
This looks fine to me in general, the only comment I have so far is that I think it would be nice to expose a `GetSite` even if it was just wrapping the `ListSite` method and iterating the results to match on ID or something. Device does something similar already: https://github.com/paultyng/go-unifi/blob/df937016b0056b2742ea4030f51e501ad3edc171/unifi/device.go#L27-L41

**Comment by kurtmc** [comment]
@paultyng Good suggestion

**Comment by kurtmc** [comment]
I've added the `GetSite` method that gets the site by it's `id` which looks like an internally used field, I am not sure if i should use that or if using `name` would be better.

**Comment by paultyng** [comment]
You could add an additional `GetSiteByName` if you wanted as well, using the internal IDs is useful if you can change the names, unsure if that's possible in Unifi though. Otherwise though this looks fine to me.

**Comment by paultyng** [comment]
I'm just realizing `UpdateSite` uses the name, argh, I guess we'll just live with this one being inconsistent but if possible would like to always just use one. Maybe its not possible.

**Review by paultyng — APPROVED** [review]

**Pull request merged**
